### ISSUE TITLE
Use the mask

### ISSUE THREAD

**Issue by kauefontes** [amarkes/brmasker-ionic#2]
I've installed and configured as exactly the instructions, but when i try to use the cnpj mask, i can't type all the numbers and got this message on console:

masker.component.js:12 The specified value "(3" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
What should i do to resolve this? :(
`<ion-input type="number" name="cnpj" [brmasker]="{mask:'00.000.000/0000-00', len:18}" [(ngModel)]="companyItem.cnpj"></ion-input>`

**Comment by amarkes** [comment]
<ion-input type="number" name="cnpj" [brmasker]="{mask:'00.000.000/0000-00', len:18}" [(ngModel)]="companyItem.cnpj"></ion-input>

exchange for

<ion-input type="text" name="cnpj" [brmasker]="{mask:'00.000.000/0000-00', len:18}" [(ngModel)]="companyItem.cnpj"></ion-input>


What's happening is that it's trying to put string inside a number

**Comment by kauefontes** [comment]
Works fine here! Thank you!

=D
