### ISSUE TITLE
Use with --prod flag

### ISSUE THREAD

**Issue by staskuban** [amarkes/brmasker-ionic#3]
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 3:31 in the original .ts file), resolving symbol AppMaskerModule in /Users/user/WebstormProjects/MDMProfileMobile/node_modules/brmasker-ionic/dist/app.module.js,

**Comment by ffoliveira** [comment]
Is this issue related with Ionic 3 version ?

**Comment by amarkes** [comment]
Hi, I tested it here and it is working properly, could it provide more details to try to see what is happening?

![captura de tela 2017-08-30 as 09 00 35](https://user-images.githubusercontent.com/6019683/29871319-b780b4f4-8d61-11e7-8d65-a75d6a4101ca.png)
![captura de tela 2017-08-30 as 09 00 56](https://user-images.githubusercontent.com/6019683/29871338-c298e7e4-8d61-11e7-90fa-429f208f353a.png)

**Comment by ffoliveira** [comment]
Did you compiled it to Android with --prod option ?

`ionic cordova build android --prod 
`

without --prod option it compiles to android without any error.

**Comment by ffoliveira** [comment]
I just found this article about a issue that seens like this one:

[https://forum.ionicframework.com/t/erro-on-run-command-ionic-cordova-run-android-prod-release/101529](https://forum.ionicframework.com/t/erro-on-run-command-ionic-cordova-run-android-prod-release/101529)

**Comment by amarkes** [comment]
I will update to the new version soon and notice here :)

**Comment by ffoliveira** [comment]
do you have an idea how soon ? no rushing....

**Comment by amarkes** [comment]
Hello, this error is generated due to **ElementRef**, so in order not to break who already uses this version, I made another version only for [IONIC 3](https://github.com/amarkes/br-masker-ionic-3)

**Comment by ffoliveira** [comment]
Great work. I will try it right now. thank you.

Muito obrigado.
